"""
Test Generator - Generate unit tests for Python, JavaScript code.
"""

import re
from dev.code_review import detect_language


PYTHON_TEST_TEMPLATE = '''"""
Unit tests for {module_name}
Auto-generated by Hybrid AI Agent
"""

import pytest
import unittest
from unittest.mock import patch, MagicMock

# TODO: adjust this import to match your project structure
# from {module_name} import {functions}


class Test{classname}(unittest.TestCase):
    """Test suite for {module_name}"""

    def setUp(self):
        """Set up test fixtures before each test."""
        pass  # TODO: initialize test objects

    def tearDown(self):
        """Clean up after each test."""
        pass

{test_methods}

    # --- Edge Cases ---

    def test_none_input(self):
        """Test that None input is handled gracefully."""
        # TODO: replace function_name with actual function
        with self.assertRaises((TypeError, ValueError)):
            function_name(None)

    def test_empty_input(self):
        """Test that empty input is handled gracefully."""
        # TODO: replace function_name with actual function
        result = function_name("")
        self.assertIsNotNone(result)

    def test_invalid_type(self):
        """Test that invalid types raise appropriate errors."""
        with self.assertRaises((TypeError, ValueError)):
            function_name(12345)  # unexpected type


if __name__ == "__main__":
    unittest.main()
'''

PYTHON_METHOD_TEMPLATE = '''    def test_{func_name}_basic(self):
        """Test {func_name} with valid input."""
        # Arrange
        # TODO: set up input values
        # Act
        # result = {func_name}(input_value)
        # Assert
        # self.assertEqual(result, expected_value)
        pass

    def test_{func_name}_edge_case(self):
        """Test {func_name} with edge case input."""
        pass
'''

JEST_TEST_TEMPLATE = '''/**
 * Tests for {module_name}
 * Auto-generated by Hybrid AI Agent
 */

// TODO: adjust import path
// const {{ {functions} }} = require('./{module_name}');

describe('{module_name}', () => {{
{test_cases}
    // Edge cases
    describe('edge cases', () => {{
        test('handles null input', () => {{
            // TODO: replace with actual function call
            expect(() => someFunction(null)).toThrow();
        }});

        test('handles empty string', () => {{
            // TODO: replace with actual function call
            // const result = someFunction('');
            // expect(result).toBeDefined();
        }});
    }});
}});
'''

JEST_CASE_TEMPLATE = '''    describe('{func_name}', () => {{
        test('returns expected result for valid input', () => {{
            // Arrange
            // const input = ...;
            // Act
            // const result = {func_name}(input);
            // Assert
            // expect(result).toEqual(expected);
        }});

        test('handles error case', () => {{
            // expect(() => {func_name}(badInput)).toThrow();
        }});
    }});
'''


def extract_python_functions(code: str):
    """Extract function names from Python code."""
    return re.findall(r"^def\s+(\w+)\s*\(", code, re.MULTILINE)


def extract_js_functions(code: str):
    """Extract function names from JavaScript code."""
    names = []
    names.extend(re.findall(r"function\s+(\w+)\s*\(", code))
    names.extend(re.findall(r"const\s+(\w+)\s*=\s*(?:async\s+)?\(", code))
    names.extend(re.findall(r"(\w+)\s*:\s*(?:async\s+)?function", code))
    return list(set(names))


class TestGenerator:
    def generate(self, code: str, language: str = "", filename: str = "") -> str:
        """Generate unit tests for provided code."""
        if not code or not code.strip():
            return "❌ No code provided."

        lang = language.lower() or detect_language(filename, code)
        module_name = (filename.replace(".py", "").replace(".js", "").replace(".ts", "") or "module")

        if lang == "python":
            return self._generate_python_tests(code, module_name)
        elif lang in ("javascript", "typescript"):
            return self._generate_jest_tests(code, module_name)
        else:
            return self._generate_generic_tests(code, lang, module_name)

    def _generate_python_tests(self, code: str, module_name: str) -> str:
        functions = extract_python_functions(code)
        classname = "".join(w.capitalize() for w in module_name.split("_"))

        if functions:
            methods = "".join(PYTHON_METHOD_TEMPLATE.format(func_name=f) for f in functions)
            func_list = ", ".join(functions)
        else:
            methods = PYTHON_METHOD_TEMPLATE.format(func_name="your_function")
            func_list = "your_function"

        test_code = PYTHON_TEST_TEMPLATE.format(
            module_name=module_name,
            classname=classname,
            functions=func_list,
            test_methods=methods,
        )

        return (
            f"```python\n{test_code}\n```\n\n"
            f"📋 Functions detected: {', '.join(functions) if functions else 'none (add manually)'}\n"
            f"💡 Run with: pytest test_{module_name}.py -v"
        )

    def _generate_jest_tests(self, code: str, module_name: str) -> str:
        functions = extract_js_functions(code)
        func_list = ", ".join(functions) if functions else "yourFunction"

        if functions:
            cases = "".join(JEST_CASE_TEMPLATE.format(func_name=f) for f in functions)
        else:
            cases = JEST_CASE_TEMPLATE.format(func_name="yourFunction")

        test_code = JEST_TEST_TEMPLATE.format(
            module_name=module_name,
            functions=func_list,
            test_cases=cases,
        )

        return (
            f"```javascript\n{test_code}\n```\n\n"
            f"📋 Functions detected: {func_list}\n"
            f"💡 Run with: npx jest {module_name}.test.js"
        )

    def _generate_generic_tests(self, code: str, language: str, module_name: str) -> str:
        return (
            f"ℹ Test generation for '{language}' is not yet supported.\n\n"
            f"Supported languages: Python, JavaScript\n\n"
            f"Manual test checklist for your code:\n"
            f"  1. Test each function with valid inputs\n"
            f"  2. Test boundary conditions (empty, null, max values)\n"
            f"  3. Test error cases and exception handling\n"
            f"  4. Test integration between components\n"
            f"  5. Test security inputs (injection strings, special chars)\n"
        )
